export const ICONS_NAME = {
  PROJECT: "folder",
  CONSTRUCTION: "office-building",
  CONTRACT: "file-document-outline",
  NOTEBOOK: "notebook-outline",
  CALENDAR: "calendar",
  CLOCK: "clock",
  ALERT: "alert",
  ALERT_CIRCLE: "alert-circle",
  CHECK_CIRCLE: "check-circle",
  DOTS_VERTICAL: "dots-vertical",
  EYE: "eye",
  PENCIL: "pencil",
  DELETE: "delete",
  ACCOUNT_PLUS: "account-plus",
  FILTER: "filter",
  IMAGE: "image",
  FILE: "file-document",
  SELECTED: "check-circle-outline",
  ACCOUNT_EDIT: "account-edit",
  ACCOUNT: "account",
  SAVE: "content-save",
  CANCEL: "close",
} as const;
